### ISSUE TITLE
SF Symbols not getting shown correctly

### ISSUE THREAD

**Issue by ifyousleep** [musa11971/Music-Bar#1]
thanks for the great program, but there is a bug - 
![image](https://user-images.githubusercontent.com/17451062/70531135-5df1dc80-1b65-11ea-8174-190f1352483a.png)

**Comment by musa11971** [comment]
Thank you for the issue @ifyousleep 

Could you please confirm the macOS version you're running?

(Apple Icon at the top left -> About This Mac)

**Comment by ifyousleep** [comment]
1) Version - 10.15.1 (19B88)
2) copy character and paste ->
![image](https://user-images.githubusercontent.com/17451062/70535256-c644bc00-1b6d-11ea-9558-2a1a5c5dfe62.png)

**Comment by musa11971** [comment]
I did some research and it seems that [SF Symbols](https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/) are not supported on macOS yet. The reason why it worked on the test devices, is probably because we have the SF Symbols browser app installed.

I'm going to try to get an update out as soon as possible to fix this.

**Comment by musa11971** [comment]
Fixed in [v1.0.1](https://github.com/musa11971/Music-Bar/releases/tag/v1.0.1).

Download it via GitHub or use the app's updater (Preferences -> Info -> Check for updates).
