### ISSUE TITLE
Clicking MusicBar in a full screen app brings me back to desktop.

### ISSUE THREAD

**Issue by AutumnalDream** [musa11971/Music-Bar#30]
Whenever I click the MusicBar in the menu bar it brings me back to a desktop instead of opening in the full screen app.

**Comment by SmallwoodDR82** [comment]
sorry to add on to this, but similar deal.  When clicking on MusicBar to pause/play/skip, macOS switches to Desktop 1 when multiple desktops are opened.  More annoying than anything.  No crash just would be nice to have it stay on the window/desktop/app you are on.

**Comment by musa11971** [comment]
The above mentioned issues are an unfortunate side-effect of:

https://github.com/musa11971/Music-Bar/blob/1d103a80c22ffcc009cbf357f980ff572c7e597e/Music%20Bar/Menu%20Bar/MenuBarManager.swift#L137

This is however needed in order to achieve the "unfocus" feature, where you can click outside the Music Bar window in order to close it. You can test the app when this is commented out and you'll notice how janky it feels.

As of right now I'm not sure what we can do about this, so I hope someone else can pitch in with any ideas/solutions! 🙂

**Comment by nicocriscuolo** [comment]
Thank you for this really nice app. I am experiencing the same issue, it would be nice to remain always on the same window.

I don't know if you can get access to the code of apps present on the App Store, but if so, then the source code of this apps could be useful to solve this problem: 

**WhatsOn**: https://apps.apple.com/us/app/whatson-now-playing/id1136082516?mt=12
**SkipTunes**: https://apps.apple.com/us/app/skip-tunes/id499695659?mt=12

Btw, the interface and the settings of your app is long way better.

Nico
